### ISSUE TITLE
more timezone linting

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/AirMonitorPlots#54]
**MazamaCoreUtils** 0.3.11 has new timezone lint rules for the date parsing functions inside of **MazamaCoreUtils**. While at the root of the **AirMonitorPlots** package, run the following to see which calls are not specifying a timezone:

```
library(MazamaCoreUtils)
lintFunctionArgs_dir("./R", timezoneLintRules) %>% 
  dplyr::filter(!includes_required)
```

Data files for `airsensor` and `ws_monitor` objects store `datetime` in UTC so that we can have a uniform time axis. We convert to local time when we need to have a timezone for plotting or calculating local-time daily averages.

So give some thought in each function whether it should be specifying `timezone = "UTC"` or `timezone = ws_monitor$meta$timezone`.

**Comment by hansmrtn** [comment]
`MazamaCoreUtils::parseDateTime` may not be properly linted(?). When a lint is preformed, the `include_required` is false even when all timezone arguments are provided.
